version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ordersystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./keycloak-init:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ordersystem
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  orderservice:
    build:
      context: .
      dockerfile: Services/OrderService/OrderService.API/Dockerfile
    container_name: orderservice
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=orders;Username=admin;Password=admin123
      - RabbitMq__Host=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
      - keycloak

  paymentservice:
    build:
      context: .
      dockerfile: Services/PaymentService/PaymentService.API/Dockerfile
    container_name: paymentservice
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=orders;Username=admin;Password=admin123
      - RabbitMq__Host=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
      - keycloak

  customerservice:
    build:
      context: .
      dockerfile: Services/CustomerService/CustomerService.API/Dockerfile
    container_name: customerservice
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=orders;Username=admin;Password=admin123
      - RabbitMq__Host=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
      - keycloak

volumes:
  postgres_data:
